tasks:
  - name: Strapi
    init: |
      cd /workspace/foodadvisor/api
      yarn install
      yarn seed
    command: yarn develop
  - name: Next.js
    init: |
      cd /workspace/foodadvisor/client &&
      yarn install
    command: yarn dev
ports:
  - port: 1337
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser
